### ISSUE TITLE
Importing of bank transactions

### ISSUE THREAD

**Issue by jsaltzman** [DotJoshJohnson/OneBudgetRequirements#5]

**Comment by DotJoshJohnson** [comment]
Development has begun! Progress for the first minimum viable product will be tracked in this pull request: OneBudget/OneBudget#1. As I get closer to finishing the boilerplate code, I will convert feature requests into stories in the OneBudget [issue tracker](https://github.com/OneBudget/OneBudget/issues). Documentation (including design documents and any other info worth sharing) will be dumped in the [wiki](https://github.com/OneBudget/OneBudget/wiki).
