### ISSUE TITLE
YNab 4 parity

### ISSUE THREAD

**Issue by sjmclean** [DotJoshJohnson/OneBudgetRequirements#7]
Hopefully we can get ynab4 parity, including the usage of red arrow right(the ability to confine overspending to that particular category)

**Comment by DotJoshJohnson** [comment]
Development has begun! Progress for the first minimum viable product will be tracked in this pull request: OneBudget/OneBudget#1. As I get closer to finishing the boilerplate code, I will convert feature requests into stories in the OneBudget [issue tracker](https://github.com/OneBudget/OneBudget/issues). Documentation (including design documents and any other info worth sharing) will be dumped in the [wiki](https://github.com/OneBudget/OneBudget/wiki).
